export default {
  formDesignId: '',
  designKey: 'diagram_Process_1683526992662',
  designName: '测试',
  designDes: '',
  designIcon: 'yanfaxiangmujiedianshenpiliucheng',
  designColor: '#0089ff',
  designGroupName: '测试',
  formInfo:
    '{"list":[{"label":"自定义字段测试组件","type":"CustomFields","options":{"help":"","width":"100%","hidden":false,"disabled":false},"rules":[{"required":false,"message":"common.please_input"}],"key":"CustomFields_1683527713001","model":"CustomFields","exposeFields":[{"label":"userName","disabled":true,"hidden":false,"type":"userName","key":"userName"},{"label":"price","disabled":true,"hidden":false,"type":"price","key":"price"}]},{"type":"table","label":"表格布局","trs":[{"tds":[{"colspan":1,"rowspan":1,"list":[{"type":"input","label":"姓名","icon":"icon-write","options":{"type":"text","width":"100%","defaultValue":"","placeholder":"","clearable":false,"maxLength":null,"addonBefore":"","addonAfter":"","hidden":false,"disabled":false},"model":"name","key":"input_1683527062121","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[{"type":"select","label":"部门","icon":"icon-xiala","options":{"width":"100%","multiple":false,"disabled":false,"clearable":false,"hidden":false,"placeholder":"请选择","dynamicKey":"","dynamic":false,"options":[{"value":"1","label":"下拉框1"},{"value":"2","label":"下拉框2"}],"showSearch":false},"model":"department","key":"select_1683527078268","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[{"type":"time","label":"填写时间","icon":"icon-time","options":{"width":"100%","defaultValue":"","disabled":false,"hidden":false,"clearable":false,"placeholder":"请选择","format":"HH:mm:ss"},"model":"time","key":"time_1683527096749","help":"","rules":[{"required":false,"message":"common.please_input"}]}]}]},{"tds":[{"colspan":1,"rowspan":1,"list":[{"type":"select","label":"下拉选择器","icon":"icon-xiala","options":{"width":"100%","multiple":false,"disabled":false,"clearable":false,"hidden":false,"placeholder":"请选择","dynamicKey":"","dynamic":false,"options":[{"value":"1","label":"下拉框1"},{"value":"2","label":"下拉框2"}],"showSearch":false},"model":"select_1683527122470","key":"select_1683527122470","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[{"type":"select","label":"下拉选择器","icon":"icon-xiala","options":{"width":"100%","multiple":false,"disabled":false,"clearable":false,"hidden":false,"placeholder":"请选择","dynamicKey":"","dynamic":false,"options":[{"value":"1","label":"下拉框1"},{"value":"2","label":"下拉框2"}],"showSearch":false},"model":"select_1683527149705","key":"select_1683527149705","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[]}]},{"tds":[{"colspan":1,"rowspan":1,"list":[{"type":"radio","label":"请加类别","icon":"icon-danxuan-cuxiantiao","options":{"disabled":false,"hidden":false,"defaultValue":"","dynamicKey":"","dynamic":false,"options":[{"value":"1","label":"事家"},{"value":"2","label":"病假"},{"value":"3","label":"婚假"}]},"model":"radio_1683527205128","key":"radio_1683527205128","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[]},{"colspan":1,"rowspan":1,"list":[]}]},{"tds":[{"colspan":3,"rowspan":1,"list":[{"type":"textarea","label":"请假原因","icon":"icon-edit","options":{"width":"100%","minRows":4,"maxRows":6,"maxLength":null,"defaultValue":"","clearable":false,"hidden":false,"disabled":false,"placeholder":""},"model":"reason","key":"textarea_1683527252882","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":0,"rowspan":1,"list":[]},{"colspan":0,"rowspan":1,"list":[]}]},{"tds":[{"colspan":1,"rowspan":1,"list":[{"type":"date","label":"请假开始时间","icon":"icon-calendar","options":{"width":"100%","defaultValue":"","rangeDefaultValue":[],"range":false,"showTime":false,"disabled":false,"hidden":false,"clearable":false,"placeholder":"请选择","rangePlaceholder":["开始时间","结束时间"],"format":"YYYY-MM-DD"},"model":"start_time","key":"date_1683527274518","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[{"type":"date","label":"请假结束时间","icon":"icon-calendar","options":{"width":"100%","defaultValue":"","rangeDefaultValue":[],"range":false,"showTime":false,"disabled":false,"hidden":false,"clearable":false,"placeholder":"请选择","rangePlaceholder":["开始时间","结束时间"],"format":"YYYY-MM-DD"},"model":"end_time","key":"date_1683527311896","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[]}]},{"tds":[{"colspan":1,"rowspan":1,"list":[{"type":"textarea","label":"部门经理签字","icon":"icon-edit","options":{"width":"100%","minRows":4,"maxRows":6,"maxLength":null,"defaultValue":"","clearable":false,"hidden":false,"disabled":false,"placeholder":""},"model":"manager_sign","key":"textarea_1683527354727","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[{"type":"textarea","label":"分管领导签字","icon":"icon-edit","options":{"width":"100%","minRows":4,"maxRows":6,"maxLength":null,"defaultValue":"","clearable":false,"hidden":false,"disabled":false,"placeholder":""},"model":"leadership","key":"textarea_1683527370492","help":"","rules":[{"required":false,"message":"common.please_input"}]}]},{"colspan":1,"rowspan":1,"list":[{"type":"textarea","label":"总经理签字","icon":"icon-edit","options":{"width":"100%","minRows":4,"maxRows":6,"maxLength":null,"defaultValue":"","clearable":false,"hidden":false,"disabled":false,"placeholder":""},"model":"boss","key":"textarea_1683527373226","help":"","rules":[{"required":false,"message":"common.please_input"}]}]}]}],"options":{"width":"100%","bordered":true,"bright":false,"small":true,"customStyle":""},"key":"table_1683527046834"}],"config":{"layout":"horizontal","labelCol":{"xs":4,"sm":4,"md":4,"lg":4,"xl":4,"xxl":4},"labelWidth":100,"labelLayout":"flex","wrapperCol":{"xs":18,"sm":18,"md":18,"lg":18,"xl":18,"xxl":18},"hideRequiredMark":false,"customStyle":"","enablePrint":false,"expressions":""}}',
  procModelXml:
    '<?xml version="1.0" encoding="UTF-8"?>\n<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="diagram_Process_1683526992662" targetNamespace="http://activiti.org/bpmn">\n  <bpmn2:process id="Process_1683526992662" name="业务流程_1683526992662" isExecutable="true">\n    <bpmn2:startEvent id="Event_1nbkupb">\n      <bpmn2:outgoing>Flow_1t2l50t</bpmn2:outgoing>\n    </bpmn2:startEvent>\n    <bpmn2:userTask id="Activity_1ul5prb">\n      <bpmn2:incoming>Flow_1t2l50t</bpmn2:incoming>\n      <bpmn2:outgoing>Flow_0m98r6r</bpmn2:outgoing>\n    </bpmn2:userTask>\n    <bpmn2:sequenceFlow id="Flow_1t2l50t" sourceRef="Event_1nbkupb" targetRef="Activity_1ul5prb" />\n    <bpmn2:userTask id="Activity_12sck8q">\n      <bpmn2:incoming>Flow_0m98r6r</bpmn2:incoming>\n      <bpmn2:outgoing>Flow_0h9vuw0</bpmn2:outgoing>\n    </bpmn2:userTask>\n    <bpmn2:sequenceFlow id="Flow_0m98r6r" sourceRef="Activity_1ul5prb" targetRef="Activity_12sck8q" />\n    <bpmn2:endEvent id="Event_1tl5tq1">\n      <bpmn2:incoming>Flow_0h9vuw0</bpmn2:incoming>\n    </bpmn2:endEvent>\n    <bpmn2:sequenceFlow id="Flow_0h9vuw0" sourceRef="Activity_12sck8q" targetRef="Event_1tl5tq1" />\n  </bpmn2:process>\n  <bpmndi:BPMNDiagram id="BPMNDiagram_1">\n    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1683526992662">\n      <bpmndi:BPMNEdge id="Flow_1t2l50t_di" bpmnElement="Flow_1t2l50t">\n        <di:waypoint x="458" y="190" />\n        <di:waypoint x="510" y="190" />\n      </bpmndi:BPMNEdge>\n      <bpmndi:BPMNEdge id="Flow_0m98r6r_di" bpmnElement="Flow_0m98r6r">\n        <di:waypoint x="610" y="190" />\n        <di:waypoint x="670" y="190" />\n      </bpmndi:BPMNEdge>\n      <bpmndi:BPMNEdge id="Flow_0h9vuw0_di" bpmnElement="Flow_0h9vuw0">\n        <di:waypoint x="770" y="190" />\n        <di:waypoint x="832" y="190" />\n      </bpmndi:BPMNEdge>\n      <bpmndi:BPMNShape id="Event_1nbkupb_di" bpmnElement="Event_1nbkupb">\n        <dc:Bounds x="422" y="172" width="36" height="36" />\n      </bpmndi:BPMNShape>\n      <bpmndi:BPMNShape id="Activity_1ul5prb_di" bpmnElement="Activity_1ul5prb">\n        <dc:Bounds x="510" y="150" width="100" height="80" />\n      </bpmndi:BPMNShape>\n      <bpmndi:BPMNShape id="Activity_12sck8q_di" bpmnElement="Activity_12sck8q">\n        <dc:Bounds x="670" y="150" width="100" height="80" />\n      </bpmndi:BPMNShape>\n      <bpmndi:BPMNShape id="Event_1tl5tq1_di" bpmnElement="Event_1tl5tq1">\n        <dc:Bounds x="832" y="172" width="36" height="36" />\n      </bpmndi:BPMNShape>\n    </bpmndi:BPMNPlane>\n  </bpmndi:BPMNDiagram>\n</bpmn2:definitions>\n',
  permissionConfig: {
    starterMembers: [],
    viewAllMembers: [],
  },
  nodeConfigs: [
    {
      nodeId: 'Activity_1ul5prb',
      taskConfig: {
        columnConfigs: [
          {
            label: '自定义字段测试组件',
            type: 'CustomFields',
            model: 'CustomFields',
            key: 'CustomFields_1683527713001',
            hidden: false,
            disabled: false,
            exposeFields: [
              {
                label: 'userName',
                disabled: true,
                hidden: false,
                type: 'userName',
                key: 'userName',
              },
              {
                label: 'price',
                disabled: true,
                hidden: false,
                type: 'price',
                key: 'price',
              },
            ],
          },
          {
            label: '姓名',
            type: 'input',
            model: 'name',
            key: 'input_1683527062121',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门',
            type: 'select',
            model: 'department',
            key: 'select_1683527078268',
            hidden: false,
            disabled: false,
          },
          {
            label: '填写时间',
            type: 'time',
            model: 'time',
            key: 'time_1683527096749',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527122470',
            key: 'select_1683527122470',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527149705',
            key: 'select_1683527149705',
            hidden: false,
            disabled: false,
          },
          {
            label: '请加类别',
            type: 'radio',
            model: 'radio_1683527205128',
            key: 'radio_1683527205128',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假原因',
            type: 'textarea',
            model: 'reason',
            key: 'textarea_1683527252882',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假开始时间',
            type: 'date',
            model: 'start_time',
            key: 'date_1683527274518',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假结束时间',
            type: 'date',
            model: 'end_time',
            key: 'date_1683527311896',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门经理签字',
            type: 'textarea',
            model: 'manager_sign',
            key: 'textarea_1683527354727',
            hidden: false,
            disabled: false,
          },
          {
            label: '分管领导签字',
            type: 'textarea',
            model: 'leadership',
            key: 'textarea_1683527370492',
            hidden: false,
            disabled: false,
          },
          {
            label: '总经理签字',
            type: 'textarea',
            model: 'boss',
            key: 'textarea_1683527373226',
            hidden: false,
            disabled: false,
          },
        ],
        members: [],
        applyerLeader: false,
        applyer: false,
      },
      copyConfig: {
        columnConfigs: [
          {
            label: '自定义字段测试组件',
            type: 'CustomFields',
            model: 'CustomFields',
            key: 'CustomFields_1683527713001',
            hidden: false,
            disabled: false,
            exposeFields: [
              {
                label: 'userName',
                disabled: true,
                hidden: false,
                type: 'userName',
                key: 'userName',
              },
              {
                label: 'price',
                disabled: true,
                hidden: false,
                type: 'price',
                key: 'price',
              },
            ],
          },
          {
            label: '姓名',
            type: 'input',
            model: 'name',
            key: 'input_1683527062121',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门',
            type: 'select',
            model: 'department',
            key: 'select_1683527078268',
            hidden: false,
            disabled: false,
          },
          {
            label: '填写时间',
            type: 'time',
            model: 'time',
            key: 'time_1683527096749',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527122470',
            key: 'select_1683527122470',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527149705',
            key: 'select_1683527149705',
            hidden: false,
            disabled: false,
          },
          {
            label: '请加类别',
            type: 'radio',
            model: 'radio_1683527205128',
            key: 'radio_1683527205128',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假原因',
            type: 'textarea',
            model: 'reason',
            key: 'textarea_1683527252882',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假开始时间',
            type: 'date',
            model: 'start_time',
            key: 'date_1683527274518',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假结束时间',
            type: 'date',
            model: 'end_time',
            key: 'date_1683527311896',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门经理签字',
            type: 'textarea',
            model: 'manager_sign',
            key: 'textarea_1683527354727',
            hidden: false,
            disabled: false,
          },
          {
            label: '分管领导签字',
            type: 'textarea',
            model: 'leadership',
            key: 'textarea_1683527370492',
            hidden: false,
            disabled: false,
          },
          {
            label: '总经理签字',
            type: 'textarea',
            model: 'boss',
            key: 'textarea_1683527373226',
            hidden: false,
            disabled: false,
          },
        ],
        members: [],
        type: 'end',
      },
      viewConfig: {
        commonConfig: {
          newest: true,
          disabled: true,
          hidden: true,
        },
        userConfig: {
          columnConfigs: [
            {
              label: '自定义字段测试组件',
              type: 'CustomFields',
              model: 'CustomFields',
              key: 'CustomFields_1683527713001',
              hidden: false,
              disabled: false,
              exposeFields: [
                {
                  label: 'userName',
                  disabled: true,
                  hidden: false,
                  type: 'userName',
                  key: 'userName',
                },
                {
                  label: 'price',
                  disabled: true,
                  hidden: false,
                  type: 'price',
                  key: 'price',
                },
              ],
            },
            {
              label: '姓名',
              type: 'input',
              model: 'name',
              key: 'input_1683527062121',
              hidden: false,
              disabled: false,
            },
            {
              label: '部门',
              type: 'select',
              model: 'department',
              key: 'select_1683527078268',
              hidden: false,
              disabled: false,
            },
            {
              label: '填写时间',
              type: 'time',
              model: 'time',
              key: 'time_1683527096749',
              hidden: false,
              disabled: false,
            },
            {
              label: '下拉选择器',
              type: 'select',
              model: 'select_1683527122470',
              key: 'select_1683527122470',
              hidden: false,
              disabled: false,
            },
            {
              label: '下拉选择器',
              type: 'select',
              model: 'select_1683527149705',
              key: 'select_1683527149705',
              hidden: false,
              disabled: false,
            },
            {
              label: '请加类别',
              type: 'radio',
              model: 'radio_1683527205128',
              key: 'radio_1683527205128',
              hidden: false,
              disabled: false,
            },
            {
              label: '请假原因',
              type: 'textarea',
              model: 'reason',
              key: 'textarea_1683527252882',
              hidden: false,
              disabled: false,
            },
            {
              label: '请假开始时间',
              type: 'date',
              model: 'start_time',
              key: 'date_1683527274518',
              hidden: false,
              disabled: false,
            },
            {
              label: '请假结束时间',
              type: 'date',
              model: 'end_time',
              key: 'date_1683527311896',
              hidden: false,
              disabled: false,
            },
            {
              label: '部门经理签字',
              type: 'textarea',
              model: 'manager_sign',
              key: 'textarea_1683527354727',
              hidden: false,
              disabled: false,
            },
            {
              label: '分管领导签字',
              type: 'textarea',
              model: 'leadership',
              key: 'textarea_1683527370492',
              hidden: false,
              disabled: false,
            },
            {
              label: '总经理签字',
              type: 'textarea',
              model: 'boss',
              key: 'textarea_1683527373226',
              hidden: false,
              disabled: false,
            },
          ],
          members: [],
        },
      },
    },
    {
      nodeId: 'Activity_12sck8q',
      taskConfig: {
        columnConfigs: [
          {
            label: '自定义字段测试组件',
            type: 'CustomFields',
            model: 'CustomFields',
            key: 'CustomFields_1683527713001',
            hidden: false,
            disabled: false,
            exposeFields: [
              {
                label: 'userName',
                disabled: true,
                hidden: false,
                type: 'userName',
                key: 'userName',
              },
              {
                label: 'price',
                disabled: true,
                hidden: false,
                type: 'price',
                key: 'price',
              },
            ],
          },
          {
            label: '姓名',
            type: 'input',
            model: 'name',
            key: 'input_1683527062121',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门',
            type: 'select',
            model: 'department',
            key: 'select_1683527078268',
            hidden: false,
            disabled: false,
          },
          {
            label: '填写时间',
            type: 'time',
            model: 'time',
            key: 'time_1683527096749',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527122470',
            key: 'select_1683527122470',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527149705',
            key: 'select_1683527149705',
            hidden: false,
            disabled: false,
          },
          {
            label: '请加类别',
            type: 'radio',
            model: 'radio_1683527205128',
            key: 'radio_1683527205128',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假原因',
            type: 'textarea',
            model: 'reason',
            key: 'textarea_1683527252882',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假开始时间',
            type: 'date',
            model: 'start_time',
            key: 'date_1683527274518',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假结束时间',
            type: 'date',
            model: 'end_time',
            key: 'date_1683527311896',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门经理签字',
            type: 'textarea',
            model: 'manager_sign',
            key: 'textarea_1683527354727',
            hidden: false,
            disabled: false,
          },
          {
            label: '分管领导签字',
            type: 'textarea',
            model: 'leadership',
            key: 'textarea_1683527370492',
            hidden: false,
            disabled: false,
          },
          {
            label: '总经理签字',
            type: 'textarea',
            model: 'boss',
            key: 'textarea_1683527373226',
            hidden: false,
            disabled: false,
          },
        ],
        members: [],
        applyerLeader: false,
        applyer: false,
      },
      copyConfig: {
        columnConfigs: [
          {
            label: '自定义字段测试组件',
            type: 'CustomFields',
            model: 'CustomFields',
            key: 'CustomFields_1683527713001',
            hidden: false,
            disabled: false,
            exposeFields: [
              {
                label: 'userName',
                disabled: true,
                hidden: false,
                type: 'userName',
                key: 'userName',
              },
              {
                label: 'price',
                disabled: true,
                hidden: false,
                type: 'price',
                key: 'price',
              },
            ],
          },
          {
            label: '姓名',
            type: 'input',
            model: 'name',
            key: 'input_1683527062121',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门',
            type: 'select',
            model: 'department',
            key: 'select_1683527078268',
            hidden: false,
            disabled: false,
          },
          {
            label: '填写时间',
            type: 'time',
            model: 'time',
            key: 'time_1683527096749',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527122470',
            key: 'select_1683527122470',
            hidden: false,
            disabled: false,
          },
          {
            label: '下拉选择器',
            type: 'select',
            model: 'select_1683527149705',
            key: 'select_1683527149705',
            hidden: false,
            disabled: false,
          },
          {
            label: '请加类别',
            type: 'radio',
            model: 'radio_1683527205128',
            key: 'radio_1683527205128',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假原因',
            type: 'textarea',
            model: 'reason',
            key: 'textarea_1683527252882',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假开始时间',
            type: 'date',
            model: 'start_time',
            key: 'date_1683527274518',
            hidden: false,
            disabled: false,
          },
          {
            label: '请假结束时间',
            type: 'date',
            model: 'end_time',
            key: 'date_1683527311896',
            hidden: false,
            disabled: false,
          },
          {
            label: '部门经理签字',
            type: 'textarea',
            model: 'manager_sign',
            key: 'textarea_1683527354727',
            hidden: false,
            disabled: false,
          },
          {
            label: '分管领导签字',
            type: 'textarea',
            model: 'leadership',
            key: 'textarea_1683527370492',
            hidden: false,
            disabled: false,
          },
          {
            label: '总经理签字',
            type: 'textarea',
            model: 'boss',
            key: 'textarea_1683527373226',
            hidden: false,
            disabled: false,
          },
        ],
        members: [],
        type: 'end',
      },
      viewConfig: {
        commonConfig: {
          newest: true,
          disabled: true,
          hidden: true,
        },
        userConfig: {
          columnConfigs: [
            {
              label: '自定义字段测试组件',
              type: 'CustomFields',
              model: 'CustomFields',
              key: 'CustomFields_1683527713001',
              hidden: false,
              disabled: false,
              exposeFields: [
                {
                  label: 'userName',
                  disabled: true,
                  hidden: false,
                  type: 'userName',
                  key: 'userName',
                },
                {
                  label: 'price',
                  disabled: true,
                  hidden: false,
                  type: 'price',
                  key: 'price',
                },
              ],
            },
            {
              label: '姓名',
              type: 'input',
              model: 'name',
              key: 'input_1683527062121',
              hidden: false,
              disabled: false,
            },
            {
              label: '部门',
              type: 'select',
              model: 'department',
              key: 'select_1683527078268',
              hidden: false,
              disabled: false,
            },
            {
              label: '填写时间',
              type: 'time',
              model: 'time',
              key: 'time_1683527096749',
              hidden: false,
              disabled: false,
            },
            {
              label: '下拉选择器',
              type: 'select',
              model: 'select_1683527122470',
              key: 'select_1683527122470',
              hidden: false,
              disabled: false,
            },
            {
              label: '下拉选择器',
              type: 'select',
              model: 'select_1683527149705',
              key: 'select_1683527149705',
              hidden: false,
              disabled: false,
            },
            {
              label: '请加类别',
              type: 'radio',
              model: 'radio_1683527205128',
              key: 'radio_1683527205128',
              hidden: false,
              disabled: false,
            },
            {
              label: '请假原因',
              type: 'textarea',
              model: 'reason',
              key: 'textarea_1683527252882',
              hidden: false,
              disabled: false,
            },
            {
              label: '请假开始时间',
              type: 'date',
              model: 'start_time',
              key: 'date_1683527274518',
              hidden: false,
              disabled: false,
            },
            {
              label: '请假结束时间',
              type: 'date',
              model: 'end_time',
              key: 'date_1683527311896',
              hidden: false,
              disabled: false,
            },
            {
              label: '部门经理签字',
              type: 'textarea',
              model: 'manager_sign',
              key: 'textarea_1683527354727',
              hidden: false,
              disabled: false,
            },
            {
              label: '分管领导签字',
              type: 'textarea',
              model: 'leadership',
              key: 'textarea_1683527370492',
              hidden: false,
              disabled: false,
            },
            {
              label: '总经理签字',
              type: 'textarea',
              model: 'boss',
              key: 'textarea_1683527373226',
              hidden: false,
              disabled: false,
            },
          ],
          members: [],
        },
      },
    },
  ],
};
